### ISSUE TITLE
Announce `swift_bazel`

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/swift_bazel#107]
## Tasks
- [x] #130 
- [x] Update `rules_spm` repository with `swift_bazel` announcement.
  - [x] cgrindel/rules_spm#210
  - [x] Add an announcement in the discussion area. cgrindel/rules_spm#211
- [x] [Announce on Slack](https://bazelbuild.slack.com/archives/CD3QY5C2X/p1673395265347389)
- [x] Post announcement in Discussions. #133 
- [x] Update Gazelle languages list with entry for Swift. bazelbuild/bazel-gazelle#1412
- [x] Write a blog post. (https://chuckgrindel.com/swift-packages-in-bazel-using-swift_bazel/)
