### ISSUE TITLE
Add better unit tests to verify build file generation in `swift_package`

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/swift_bazel#177]
I decided to  update the tests for `swiftpkg_build_files` to do a diff against the generated rules.

## Tasks
- [x] Add executable product referencing executable Swift target.
- [x] Add simple `cc_library`.
- [x] Add simple `objc_library`.
- [x] Add `cc_library` with `path`, `source_paths`, and `exclude_paths`. (Example `abseil`)
- [x] Add conditional `define` for Swift target.
- [x] Add conditional `define` for clang target.
- [x] Add conditional `headerSearchPath` for clang target.
- [x] Add conditional `unsafeFlags` for Swift target.
- [x] Add conditional `unsafeFlags` for clang target.
- [x] Swift library that uses `XCTest` should be marked `testonly  = True`.
