### ISSUE TITLE
Update Gazelle extension to resolve to products

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/swift_bazel#194]
The current implementation attempts to pull in the targets by the modules that they provide. This is not sufficient for some packages. Some packages with clang and objc targets use the targets as shorthand for including headers and other definitions (e.g. the Firebase target in the firebase-ios-sdk) in other targets. This leads to targets that define a Swift module but may not be complete for compilation. 

This situation leads to another problem. The list of modules available in a product cannot be determined by looking at the targets directly associated with the product. Luckily, SPM does provide product membership information for each target in its description JSON. Hence the modules provided by a product are the list of targets/modules that have a membership in the product.

To resolve dependencies when generating Swift rules from source files, we need to do the following:
1. Identify the modules used in the source files.
2. For each module, try to resolve the module to an internal target. If one is not found add it to a list of modules for external resolution.
3. For the list of external modules, identify the products that provide the modules. (Restrict the lookup to products provided by direct dependencies) The list of products then needs to be reduced to the smallest subset that will satisfy the list.
4. Generate the list of Bazel labels using the products. (Important part!)

## Tasks
- [x] Add `product_memberships` to `swiftpkg.Target`.
- [x] Write the product memberships to the module index.
- [x] When reading in the dependency index (includes products and modules), need to add lookup of module name to product.
- [x] Add function to dependency index to perform the resolution discussed above.
- [ ] #199

**Comment by cgrindel** [comment]
Accidentally closed.

**Comment by cgrindel** [comment]
Decided to track the Starlark work in a separate issue.
